# -*- coding: utf-8 -*-
"""Abalone_SVM_js

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScBZakwE00tubWuM17sCpVtko6S9wVSj
"""

# Step 1 - Import all required binaries for applying SVM regressor on abalone data
import pandas as pd
import numpy as np
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Step 2 - Read data into a data frame
names = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']
df = pd.read_csv('/content/abalone.data', names=names, sep=',')

df.head()

df = df.drop('Sex', axis=1)

df.columns

# Step 4 - Define X and y
X = df[['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']]
y = df['Rings']

# Step 5 - Split X and y into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=45)

sv = SVR(kernel='rbf')

sv.fit(X_train, y_train)

sv.score(X_test, y_test)



y_pred = sv.predict(X_test)
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
display(results.head())

"""# Abalone Ring Prediction using Support Vector Regression

This project aims to predict the age of abalone by predicting the number of rings using a Support Vector Regression (SVR) model.

## Data

The dataset used is the Abalone Data Set, which contains various physical measurements of abalone. The 'Sex' column was dropped as part of the preprocessing. The target variable is 'Rings', which represents the number of rings and corresponds to the age of the abalone.

## Model

A Support Vector Regression (SVR) model with a Radial Basis Function (RBF) kernel was used for prediction. The data was split into training and testing sets (80/20 split).

## Results

The SVR model with an RBF kernel achieved a score of {{sv.score(X_test, y_test):.2f}} on the test set.

The scatter plot of Actual vs. Predicted Rings shows that the model is able to capture some of the variance in the data, but there is still a significant spread in the predictions, particularly for higher numbers of rings. This suggests that the model's ability to predict the exact number of rings is limited.

## Interpretation

The current SVR model provides a moderate level of accuracy in predicting the number of abalone rings. While the RBF kernel improved the performance compared to a linear kernel, the scatter plot indicates that the model struggles with precise predictions, especially for older abalone with more rings. This could be due to the inherent variability in abalone growth or limitations of the current model and features. Further exploration, such as feature engineering, hyperparameter tuning, or trying different models (like the classification approach discussed earlier), could potentially improve the prediction accuracy.
"""

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Rings")
plt.ylabel("Predicted Rings")
plt.title("Actual vs. Predicted Rings (SVR with RBF Kernel)")
plt.show()